### ISSUE TITLE
Stuck in Header after inserting watermark

### ISSUE THREAD

**Issue by GGarven** [damat/SimpleWatermark#1]
Hi, I was able to successfully add a watermark to a Google Doc (only wish is could it be bigger and other choices of font), but now find that I cannot return to editing the document itself - how do I get out of the "Header" screen?

**Comment by damat** [comment]
Hi there,
Just click in the document, that will select the watermark, hit delete key. After that you'll be able to edit the document and add the watermark after your edits.

**Comment by GGarven** [comment]
Do you mean that we have to add the watermark when all edits are complete....and then delete and add again if further edits are required?

Graham Garven | Partner
M: +62 818 731623 | D: +62 21 719 1246 | W: www.vdb-loi.com | Skype: gjgarven
Office: T: +62 21 718 3415 Plaza Bisnis Kemang Suite 211, Jl. Kemang Raya No.2 Jakarta 12730, Indonesia
· OUR REGIONAL APPROACH - TAX. READ MORE
· CLEAR, CONCISE, COMPREHENSIVE - INDONESIAN TAX ESSENTIALS IN ONE PAGE. READ MORE

This e-mail is confidential and may also be privileged. If you are not the intended recipient, please notify the sender immediately,
delete it from your system and do not copy, disseminate, distribute or disclose any information contained therein. Thank you.

**Comment by damat** [comment]
Unfortunately, yes. Google Docs API is extremely limited, and we just can't
add watermark anyhow else except as an image on top of everything.

Dmitry Astapkovich
dmitry.astapkovich@gmail.com

**Comment by GGarven** [comment]
Ok thanks

Graham Garven | Partner
M: +62 818 731623 | D: +62 21 719 1246 | W: www.vdb-loi.com | Skype: gjgarven
Office: T: +62 21 718 3415 Plaza Bisnis Kemang Suite 211, Jl. Kemang Raya No.2 Jakarta 12730, Indonesia
· OUR REGIONAL APPROACH - TAX. READ MORE
· CLEAR, CONCISE, COMPREHENSIVE - INDONESIAN TAX ESSENTIALS IN ONE PAGE. READ MORE

This e-mail is confidential and may also be privileged. If you are not the intended recipient, please notify the sender immediately,
delete it from your system and do not copy, disseminate, distribute or disclose any information contained therein. Thank you.
