### ISSUE TITLE
Watermarks for landscape pages

### ISSUE THREAD

**Issue by Katrina9** [damat/SimpleWatermark#10]
Can you please let me know how to change the rotation of the page to landscape before applying the watermarks.
Thank you

**Comment by damat** [comment]
Sorry for the late reply. Not sure if I understand the question, but have you tried File > Page Setup?
![image](https://user-images.githubusercontent.com/914556/94112006-7bbad480-fe4d-11ea-9ff5-9a537a1edb20.png)
