### ISSUE TITLE
How to remove the watermark?

### ISSUE THREAD

**Issue by gabbygirl99** [damat/SimpleWatermark#11]
I can't seem to remove it, it will only let me add additional watermarks.

**Comment by damat** [comment]
Hi Gabby, 
You need to select the watermark and hit delete key. Please let me know if it works for you.

**Comment by gabbygirl99** [comment]
Looks like you need to try a few clicks to properly select it. It wants to select the text underneath / flip-flopping to the watermark, somewhat unpredictably. I've tried switching back to Chrome and now it's easier. Was impossible on my other PC using Firefox.
Thanks! Feel stupid now that I had to ask this. :/

**Comment by damat** [comment]
Oh, no worries, Gabby! In the next versions we plan to add a separate delete button to the panel. That would be helpful since it's not perfect at all right now

**Comment by damat** [comment]
We have upgrade the app. Now you can do export to PDF directly without adding watermark to the document.
