### ISSUE TITLE
Headers font size change after Watermark added

### ISSUE THREAD

**Issue by wreckit-Ralph** [damat/SimpleWatermark#3]
In my document, I have a header that is formatted as Title, and on another line within the header a date that is formatted as normal text.

After creating a watermark, all text in the header is reduced to a font size of 1.

**Comment by damat** [comment]
Hello Ralph,

I was not able to reproduce that bug =( Could you please share the doc with me? da@colined.com

**Comment by damat** [comment]
Closing with no response from user
