### ISSUE TITLE
How to remove the watermark ?

### ISSUE THREAD

**Issue by cguisebrown** [damat/SimpleWatermark#5]
Hi

there is no menu item to remove the watermark and editing dod not work. I tried to select it and delete or "cut" it but this only works after much "fiddling"

**Comment by damat** [comment]
Unfortunately, there's a GSuite API bug that sometimes results into insertion of multiply images. So that's way sometimes you just had to press delete button several times. Sorry for that, but Google just hasn't done enough for developers =(

**Comment by crapasta** [comment]
I had to crop the image, make it smaller then I was able to delete it

**Comment by damat** [comment]
I'm glad you've found a way to solve it!
