### ISSUE TITLE
Watermark issues

### ISSUE THREAD

**Issue by Lucy123123** [damat/SimpleWatermark#8]
It just keeps telling me
ScriptError: Authorisation is required to perform that action.
And will not let me put on the watermark

**Comment by rolandohgarcia** [comment]
how do you delete a watermark?

**Comment by damat** [comment]
@Lucy123123, sorry for the late reply. Sometimes Google API works that way =( We neither can't reproduce nor fix this issue. 

@rolandohgarcia, you need to select it and delete by either pressing delete button or by using context menu

**Comment by hrdrckx** [comment]
> It just keeps telling me
> ScriptError: Authorisation is required to perform that action.
> And will not let me put on the watermark

Same here.  what is causing this?

**Comment by damat** [comment]
@hrdrckx, our guess is it's a permission issue . Seems like a user can install the add-on, but don't have a permission to run it. The problem is we can't reproduce it. If there are any ideas on what should set in Admin to achieve this, please share.

**Comment by hrdrckx** [comment]
problem still persisting.
could it be a domain install vs individual install thing?

**Comment by damat** [comment]
@hrdrckx, we checked that both on individual and domain install. And there's literally zero permission settings that can prevent users from running an app installed to a domain =(

**Comment by pcaridade** [comment]
Solved the problem of ScriptError: Authorisation is required to perform that action (I think). This error appears when you have multiple goggle accounts with logged on. Tried to use incognito mode with only one account logged in and it worked.

I have a small question. Maybe an add-on. Is it possible to put the watermarked image with an option to be under the text?

**Comment by damat** [comment]
Oh, thank you for the hint @pcaridade! We'll check if there's anything we can support for multi accounts. 

As for under the text placement, unfortunately it's technically possible in Google Docs. Would love to add this option, but can't =(
